<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Currency;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      

        // $currencies = [
        //     [
        //         'code'       => 'USD',
        //         'symbol'     => '$',
        //         'created_at' => now(),
        //     ],

        //     [
        //         'code'       => 'Rs',
        //         'symbol'     => '₹',
        //         'created_at' => now(),
        //     ],

        //     [
        //         'code'       => 'BDT',
        //         'symbol'     => '৳',
        //         'created_at' => now(),
        //     ]

        // ];

        $currencies = array(
            array("country"=>"Afghanistan","currency"=>"Afghani","code"=>"AFN","symbol"=>"؋"),
            array("country"=>"Åland Islands","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Albania","currency"=>"Lek","code"=>"ALL","symbol"=>"Lek"),
            array("country"=>"American Samoa","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Andorra","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Argentina","currency"=>"Argentine Peso","code"=>"ARS","symbol"=>"$"),
            array("country"=>"Australia","currency"=>"Australian Dollar","code"=>"AUD","symbol"=>"$"),
            array("country"=>"Austria","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Bahamas","currency"=>"Bahamian Dollar","code"=>"BSD","symbol"=>"$"),
            array("country"=>"Bangladesh","currency"=>"Taka","code"=>"BDT","symbol"=>"৳"),
            array("country"=>"Barbados","currency"=>"Barbados Dollar","code"=>"BBD","symbol"=>"$"),
            array("country"=>"Belgium","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Belize","currency"=>"Belize Dollar","code"=>"BZD","symbol"=>"BZ$"),
            array("country"=>"Bhutan","currency"=>"Indian Rupee","code"=>"INR","symbol"=>"₹"),
            array("country"=>"Bonaire, Sint Eustatius And Saba","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Brazil","currency"=>"Brazilian Real","code"=>"BRL","symbol"=>"R$"),
            array("country"=>"British Indian Ocean Territory","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Bulgaria","currency"=>"Bulgarian Lev","code"=>"BGN","symbol"=>"лв"),
            array("country"=>"Cambodia","currency"=>"Riel","code"=>"KHR","symbol"=>"៛"),
            array("country"=>"Canada","currency"=>"Canadian Dollar","code"=>"CAD","symbol"=>"$"),
            array("country"=>"Chile","currency"=>"Chilean Peso","code"=>"CLP","symbol"=>"$"),
            array("country"=>"China","currency"=>"Yuan Renminbi","code"=>"CNY","symbol"=>"¥"),
            array("country"=>"Colombia","currency"=>"Colombian Peso","code"=>"COP","symbol"=>"$"),
            array("country"=>"Cook Islands","currency"=>"New Zealand Dollar","code"=>"NZD","symbol"=>"$"),
            array("country"=>"Croatia","currency"=>"Kuna","code"=>"HRK","symbol"=>"kn"),
            array("country"=>"Cyprus","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Czechia","currency"=>"Czech Koruna","code"=>"CZK","symbol"=>"Kč"),
            array("country"=>"Denmark","currency"=>"Danish Krone","code"=>"DKK","symbol"=>"kr"),
            array("country"=>"Ecuador","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"El Salvador","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Estonia","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"European Union","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Finland","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"France","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"French Guiana","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"French Southern Territories","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Georgia","currency"=>"Lari","code"=>"GEL","symbol"=>"₾"),
            array("country"=>"Germany","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Greece","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Guadeloupe","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Guam","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Guernsey","currency"=>"Pound Sterling","code"=>"GBP","symbol"=>"£"),
            array("country"=>"Haiti","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Holy See (Vatican)","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Hong Kong","currency"=>"Hong Kong Dollar","code"=>"HKD","symbol"=>"$"),
            array("country"=>"Hungary","currency"=>"Forint","code"=>"HUF","symbol"=>"ft"),
            array("country"=>"India","currency"=>"Indian Rupee","code"=>"INR","symbol"=>"₹"),
            array("country"=>"Indonesia","currency"=>"Rupiah","code"=>"IDR","symbol"=>"Rp"),
            array("country"=>"Ireland","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Isle Of Man","currency"=>"Pound Sterling","code"=>"GBP","symbol"=>"£"),
            array("country"=>"Israel","currency"=>"New Israeli Sheqel","code"=>"ILS","symbol"=>"₪"),
            array("country"=>"Italy","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Japan","currency"=>"Yen","code"=>"JPY","symbol"=>"¥"),
            array("country"=>"Jersey","currency"=>"Pound Sterling","code"=>"GBP","symbol"=>"£"),
            array("country"=>"Kenya","currency"=>"Kenyan Shilling","code"=>"KES","symbol"=>"Ksh"),
            array("country"=>"Korea (the Republic Of)","currency"=>"Won","code"=>"KRW","symbol"=>"₩"),
            array("country"=>"Latvia","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Lithuania","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Luxembourg","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Malaysia","currency"=>"Malaysian Ringgit","code"=>"MYR","symbol"=>"RM"),
            array("country"=>"Malta","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Marshall Islands","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Martinique","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Mayotte","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Mexico","currency"=>"Mexican Peso","code"=>"MXN","symbol"=>"$"),
            array("country"=>"Micronesia","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Monaco","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Montenegro","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Morocco","currency"=>"Moroccan Dirham","code"=>"MAD","symbol"=>" .د.م "),
            array("country"=>"Netherlands","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"New Zealand","currency"=>"New Zealand Dollar","code"=>"NZD","symbol"=>"$"),
            array("country"=>"Nigeria","currency"=>"Naira","code"=>"NGN","symbol"=>"₦"),
            array("country"=>"Niue","currency"=>"New Zealand Dollar","code"=>"NZD","symbol"=>"$"),
            array("country"=>"Northern Mariana Islands","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Norway","currency"=>"Norwegian Krone","code"=>"NOK","symbol"=>"kr"),
            array("country"=>"Pakistan","currency"=>"Pakistan Rupee","code"=>"PKR","symbol"=>"Rs"),
            array("country"=>"Palau","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Panama","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Peru","currency"=>"Sol","code"=>"PEN","symbol"=>"S"),
            array("country"=>"Philippines","currency"=>"Philippine Peso","code"=>"PHP","symbol"=>"₱"),
            array("country"=>"Pitcairn","currency"=>"New Zealand Dollar","code"=>"NZD","symbol"=>"$"),
            array("country"=>"Poland","currency"=>"Zloty","code"=>"PLN","symbol"=>"zł"),
            array("country"=>"Portugal","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Puerto Rico","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Réunion","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Romania","currency"=>"Romanian Leu","code"=>"RON","symbol"=>"lei"),
            array("country"=>"Russian Federation","currency"=>"Russian Ruble","code"=>"RUB","symbol"=>"₽"),
            array("country"=>"Saint Barthélemy","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Saint Martin (French Part)","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Saint Pierre And Miquelon","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"San Marino","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Singapore","currency"=>"Singapore Dollar","code"=>"SGD","symbol"=>"$"),
            array("country"=>"Slovakia","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Slovenia","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"South Africa","currency"=>"Rand","code"=>"ZAR","symbol"=>"R"),
            array("country"=>"Spain","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Sri Lanka","currency"=>"Sri Lanka Rupee","code"=>"LKR","symbol"=>"Rs"),
            array("country"=>"Sweden","currency"=>"Swedish Krona","code"=>"SEK","symbol"=>"kr"),
            array("country"=>"Thailand","currency"=>"Baht","code"=>"THB","symbol"=>"฿"),
            array("country"=>"Timor-leste","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Tokelau","currency"=>"New Zealand Dollar","code"=>"NZD","symbol"=>"$"),
            array("country"=>"Turkey","currency"=>"Turkish Lira","code"=>"TRY","symbol"=>"₺"),
            array("country"=>"Turks And Caicos Islands","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Ukraine","currency"=>"Hryvnia","code"=>"UAH","symbol"=>"₴"),
            array("country"=>"United Arab Emirates","currency"=>"UAE Dirham","code"=>"AED","symbol"=>"د.إ"),
            array("country"=>"United Kingdom Of Great Britain And Northern Ireland","currency"=>"Pound Sterling","code"=>"GBP","symbol"=>"£"),
            array("country"=>"United States Minor Outlying Islands","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"United States Of America","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Vietnam","currency"=>"Dong","code"=>"VND","symbol"=>"₫"),
            array("country"=>"Virgin Islands (British)","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Virgin Islands (U.S.)","currency"=>"US Dollar","code"=>"USD","symbol"=>"$"),
            array("country"=>"Albania","currency"=>"Leke","code"=>"ALL","symbol"=>"Lek"),
            array("country"=>"America","currency"=>"Dollars","code"=>"USD","symbol"=>"$"),
            array("country"=>"Afghanistan","currency"=>"Afghanis","code"=>"AFN","symbol"=>"؋"),
            array("country"=>"Argentina","currency"=>"Pesos","code"=>"ARS","symbol"=>"$"),
            array("country"=>"Aruba","currency"=>"Guilders","code"=>"AWG","symbol"=>"ƒ"),
            array("country"=>"Australia","currency"=>"Dollars","code"=>"AUD","symbol"=>"$"),
            array("country"=>"Azerbaijan","currency"=>"New Manats","code"=>"AZN","symbol"=>"ман"),
            array("country"=>"Bahamas","currency"=>"Dollars","code"=>"BSD","symbol"=>"$"),
            array("country"=>"Barbados","currency"=>"Dollars","code"=>"BBD","symbol"=>"$"),
            array("country"=>"Belarus","currency"=>"Rubles","code"=>"BYR","symbol"=>"p."),
            array("country"=>"Belgium","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Beliz","currency"=>"Dollars","code"=>"BZD","symbol"=>"BZ$"),
            array("country"=>"Bermuda","currency"=>"Dollars","code"=>"BMD","symbol"=>"$"),
            array("country"=>"Bolivia","currency"=>"Bolivianos","code"=>"BOB","symbol"=>'$b'),
            array("country"=>"Bosnia and Herzegovina","currency"=>"Convertible Marka","code"=>"BAM","symbol"=>"KM"),
            array("country"=>"Botswana","currency"=>"Pula","code"=>"BWP","symbol"=>"P"),
            array("country"=>"Bulgaria","currency"=>"Leva","code"=>"BGN","symbol"=>"лв"),
            array("country"=>"Brazil","currency"=>"Reais","code"=>"BRL","symbol"=>"R$"),
            array("country"=>"Britain (United Kingdom)","currency"=>"Pounds","code"=>"GBP","symbol"=>"£"),
            array("country"=>"Brunei Darussalam","currency"=>"Dollars","code"=>"BND","symbol"=>"$"),
            array("country"=>"Cambodia","currency"=>"Riels","code"=>"KHR","symbol"=>"៛"),
            array("country"=>"Canada","currency"=>"Dollars","code"=>"CAD","symbol"=>"$"),
            array("country"=>"Cayman Islands","currency"=>"Dollars","code"=>"KYD","symbol"=>"$"),
            array("country"=>"Chile","currency"=>"Pesos","code"=>"CLP","symbol"=>"$"),
            array("country"=>"China","currency"=>"Yuan Renminbi","code"=>"CNY","symbol"=>"¥"),
            array("country"=>"Colombia","currency"=>"Pesos","code"=>"COP","symbol"=>"$"),
            array("country"=>"Costa Rica","currency"=>"Colón","code"=>"CRC","symbol"=>"₡"),
            array("country"=>"Croatia","currency"=>"Kuna","code"=>"HRK","symbol"=>"kn"),
            array("country"=>"Cuba","currency"=>"Pesos","code"=>"CUP","symbol"=>"₱"),
            array("country"=>"Cyprus","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Czech Republic","currency"=>"Koruny","code"=>"CZK","symbol"=>"Kč"),
            array("country"=>"Denmark","currency"=>"Kroner","code"=>"DKK","symbol"=>"kr"),
            array("country"=>"Dominican Republic","currency"=>"Pesos","code"=>"DOP ","symbol"=>"RD$"),
            array("country"=>"East Caribbean","currency"=>"Dollars","code"=>"XCD","symbol"=>"$"),
            array("country"=>"Egypt","currency"=>"Pounds","code"=>"EGP","symbol"=>"£"),
            array("country"=>"El Salvador","currency"=>"Colones","code"=>"SVC","symbol"=>"$"),
            array("country"=>"England (United Kingdom)","currency"=>"Pounds","code"=>"GBP","symbol"=>"£"),
            array("country"=>"Euro","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Falkland Islands","currency"=>"Pounds","code"=>"FKP","symbol"=>"£"),
            array("country"=>"Fiji","currency"=>"Dollars","code"=>"FJD","symbol"=>"$"),
            array("country"=>"France","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Ghana","currency"=>"Cedis","code"=>"GHC","symbol"=>"¢"),
            array("country"=>"Gibraltar","currency"=>"Pounds","code"=>"GIP","symbol"=>"£"),
            array("country"=>"Greece","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Guatemala","currency"=>"Quetzales","code"=>"GTQ","symbol"=>"Q"),
            array("country"=>"Guernsey","currency"=>"Pounds","code"=>"GGP","symbol"=>"£"),
            array("country"=>"Guyana","currency"=>"Dollars","code"=>"GYD","symbol"=>"$"),
            array("country"=>"Holland (Netherlands)","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Honduras","currency"=>"Lempiras","code"=>"HNL","symbol"=>"L"),
            array("country"=>"Hong Kong","currency"=>"Dollars","code"=>"HKD","symbol"=>"$"),
            array("country"=>"Hungary","currency"=>"Forint","code"=>"HUF","symbol"=>"Ft"),
            array("country"=>"Iceland","currency"=>"Kronur","code"=>"ISK","symbol"=>"kr"),
            array("country"=>"India","currency"=>"Rupees","code"=>"INR","symbol"=>"Rp"),
            array("country"=>"Indonesia","currency"=>"Rupiahs","code"=>"IDR","symbol"=>"Rp"),
            array("country"=>"Iran","currency"=>"Rials","code"=>"IRR","symbol"=>"﷼"),
            array("country"=>"Ireland","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Isle of Man","currency"=>"Pounds","code"=>"IMP","symbol"=>"£"),
            array("country"=>"Israel","currency"=>"New Shekels","code"=>"ILS","symbol"=>"₪"),
            array("country"=>"Italy","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Jamaica","currency"=>"Dollars","code"=>"JMD","symbol"=>"J$"),
            array("country"=>"Japan","currency"=>"Yen","code"=>"JPY","symbol"=>"¥"),
            array("country"=>"Jersey","currency"=>"Pounds","code"=>"JEP","symbol"=>"£"),
            array("country"=>"Kazakhstan","currency"=>"Tenge","code"=>"KZT","symbol"=>"лв"),
            array("country"=>"Korea (North)","currency"=>"Won","code"=>"KPW","symbol"=>"₩"),
            array("country"=>"Korea (South)","currency"=>"Won","code"=>"KRW","symbol"=>"₩"),
            array("country"=>"Kyrgyzstan","currency"=>"Soms","code"=>"KGS","symbol"=>"лв"),
            array("country"=>"Laos","currency"=>"Kips","code"=>"LAK","symbol"=>"₭"),
            array("country"=>"Latvia","currency"=>"Lati","code"=>"LVL","symbol"=>"Ls"),
            array("country"=>"Lebanon","currency"=>"Pounds","code"=>"LBP","symbol"=>"£"),
            array("country"=>"Liberia","currency"=>"Dollars","code"=>"LRD","symbol"=>"$"),
            array("country"=>"Liechtenstein","currency"=>"Switzerland Francs","code"=>"CHF","symbol"=>"CHF"),
            array("country"=>"Lithuania","currency"=>"Litai","code"=>"LTL","symbol"=>"Lt"),
            array("country"=>"Luxembourg","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Macedonia","currency"=>"Denars","code"=>"MKD","symbol"=>"ден"),
            array("country"=>"Malaysia","currency"=>"Ringgits","code"=>"MYR","symbol"=>"RM"),
            array("country"=>"Malta","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Mauritius","currency"=>"Rupees","code"=>"MUR","symbol"=>"₨"),
            array("country"=>"Mexico","currency"=>"Pesos","code"=>"MXN","symbol"=>"$"),
            array("country"=>"Mongolia","currency"=>"Tugriks","code"=>"MNT","symbol"=>"₮"),
            array("country"=>"Mozambique","currency"=>"Meticais","code"=>"MZN","symbol"=>"MT"),
            array("country"=>"Namibia","currency"=>"Dollars","code"=>"NAD","symbol"=>"$"),
            array("country"=>"Nepal","currency"=>"Rupees","code"=>"NPR","symbol"=>"₨"),
            array("country"=>"Netherlands Antilles","currency"=>"Guilders","code"=>"ANG","symbol"=>"ƒ"),
            array("country"=>"Netherlands","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"New Zealand","currency"=>"Dollars","code"=>"NZD","symbol"=>"$"),
            array("country"=>"Nicaragua","currency"=>"Cordobas","code"=>"NIO","symbol"=>"C$"),
            array("country"=>"Nigeria","currency"=>"Nairas","code"=>"NGN","symbol"=>"₦"),
            array("country"=>"North Korea","currency"=>"Won","code"=>"KPW","symbol"=>"₩"),
            array("country"=>"Norway","currency"=>"Krone","code"=>"NOK","symbol"=>"kr"),
            array("country"=>"Oman","currency"=>"Rials","code"=>"OMR","symbol"=>"﷼"),
            array("country"=>"Pakistan","currency"=>"Rupees","code"=>"PKR","symbol"=>"₨"),
            array("country"=>"Panama","currency"=>"Balboa","code"=>"PAB","symbol"=>"B/."),
            array("country"=>"Paraguay","currency"=>"Guarani","code"=>"PYG","symbol"=>"Gs"),
            array("country"=>"Peru","currency"=>"Nuevos Soles","code"=>"PEN","symbol"=>"S/."),
            array("country"=>"Philippines","currency"=>"Pesos","code"=>"PHP","symbol"=>"Php"),
            array("country"=>"Poland","currency"=>"Zlotych","code"=>"PLN","symbol"=>"zł"),
            array("country"=>"Qatar","currency"=>"Rials","code"=>"QAR","symbol"=>"﷼"),
            array("country"=>"Romania","currency"=>"New Lei","code"=>"RON","symbol"=>"lei"),
            array("country"=>"Russia","currency"=>"Rubles","code"=>"RUB","symbol"=>"руб"),
            array("country"=>"Saint Helena","currency"=>"Pounds","code"=>"SHP","symbol"=>"£"),
            array("country"=>"Saudi Arabia","currency"=>"Riyals","code"=>"SAR","symbol"=>"﷼"),
            array("country"=>"Serbia","currency"=>"Dinars","code"=>"RSD","symbol"=>"Дин."),
            array("country"=>"Seychelles","currency"=>"Rupees","code"=>"SCR","symbol"=>"₨"),
            array("country"=>"Singapore","currency"=>"Dollars","code"=>"SGD","symbol"=>"$"),
            array("country"=>"Slovenia","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Solomon Islands","currency"=>"Dollars","code"=>"SBD","symbol"=>"$"),
            array("country"=>"Somalia","currency"=>"Shillings","code"=>"SOS","symbol"=>"S"),
            array("country"=>"South Africa","currency"=>"Rand","code"=>"ZAR","symbol"=>"R"),
            array("country"=>"South Korea","currency"=>"Won","code"=>"KRW","symbol"=>"₩"),
            array("country"=>"Spain","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Sri Lanka","currency"=>"Rupees","code"=>"LKR","symbol"=>"₨"),
            array("country"=>"Sweden","currency"=>"Kronor","code"=>"SEK","symbol"=>"kr"),
            array("country"=>"Switzerland","currency"=>"Francs","code"=>"CHF","symbol"=>"CHF"),
            array("country"=>"Suriname","currency"=>"Dollars","code"=>"SRD","symbol"=>"$"),
            array("country"=>"Syria","currency"=>"Pounds","code"=>"SYP","symbol"=>"£"),
            array("country"=>"Taiwan","currency"=>"New Dollars","code"=>"TWD","symbol"=>"NT$"),
            array("country"=>"Thailand","currency"=>"Baht","code"=>"THB","symbol"=>"฿"),
            array("country"=>"Trinidad and Tobago","currency"=>"Dollars","code"=>"TTD","symbol"=>"TT$"),
            array("country"=>"Turkey","currency"=>"Lira","code"=>"TRY","symbol"=>"TL"),
            array("country"=>"Turkey","currency"=>"Liras","code"=>"TRL","symbol"=>"£"),
            array("country"=>"Tuvalu","currency"=>"Dollars","code"=>"TVD","symbol"=>"$"),
            array("country"=>"Ukraine","currency"=>"Hryvnia","code"=>"UAH","symbol"=>"₴"),
            array("country"=>"United Kingdom","currency"=>"Pounds","code"=>"GBP","symbol"=>"£"),
            array("country"=>"United States of America","currency"=>"Dollars","code"=>"USD","symbol"=>"$"),
            array("country"=>"Uruguay","currency"=>"Pesos","code"=>"UYU","symbol"=>'$U'),
            array("country"=>"Uzbekistan","currency"=>"Sums","code"=>"UZS","symbol"=>"лв"),
            array("country"=>"Vatican City","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
            array("country"=>"Venezuela","currency"=>"Bolivares Fuertes","code"=>"VEF","symbol"=>"Bs"),
            array("country"=>"Vietnam","currency"=>"Dong","code"=>"VND","symbol"=>"₫"),
            array("country"=>"Yemen","currency"=>"Rials","code"=>"YER","symbol"=>"﷼"),
            array("country"=>"Zimbabwe","currency"=>"Zimbabwe Dollars","code"=>"ZWD","symbol"=>"Z$"),
            array("country"=>"India","currency"=>"Rupees","code"=>"INR","symbol"=>"₹"),
        );

        DB::table('currencies')->insert($currencies);
    }
}
